/* World of God: presentation and local persistence. No network dependencies. */
(() => {'use strict';
const $=id=>document.getElementById(id), canvas=$('world'), ctx=canvas.getContext('2d');
const names={valley:'豐饒河谷',dry:'乾燥盆地',islands:'群島微光'};
const taskNames={farm:'耕作',farming:'耕作',forage:'採集',foraging:'採集',pray:'祈禱',praying:'祈禱',rest:'休息',resting:'休息',eat:'進食',eating:'進食'};
const stageNames={issued:'已傳下',heard:'已聽見',interpreted:'已解讀',accepted:'接受',deferred:'暫緩',refused:'拒絕',rejected:'拒絕',attempted:'嘗試中',completed:'完成',failed:'未完成',consequences:'結果浮現'};
let state,paused=true,speed=1,selectedTown=0,selectedPerson=null,armed=null,hover=null,db=null,storageOK=true,archiveSeq=0,worldKey='',toastTimer,frame=0,accum=0,lastFrame=0,preset='valley';
let markers=[],seen={miracle:false,oracle:false,consequence:false};
const num=(x,n=0)=>Number(x||0).toFixed(n), esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400)}
function store(key,value){try{localStorage.setItem(key,value);return true}catch(e){storageOK=false;storageMessage();return false}}
function read(key){try{return localStorage.getItem(key)}catch(e){storageOK=false;storageMessage();return null}}
function storageMessage(){$('storage').textContent=storageOK?(db?'本機儲存 · 歷史持續寫入':'本機存檔 · 歷史僅保留近期'):'⚠ 無法持久儲存，請使用匯出';}
function openDB(){try{const req=indexedDB.open('wog-history-v1',1);req.onupgradeneeded=()=>{const s=req.result.createObjectStore('events',{keyPath:'key'});s.createIndex('world','world');};req.onsuccess=()=>{db=req.result;storageMessage();archiveEvents()};req.onerror=()=>{storageMessage();toast('歷史檔案不可用；近期事件仍隨存檔保存。請定期匯出。')}}catch(e){storageMessage()}}
function archiveEvents(){if(!state||!db)return;const fresh=state.events.filter(e=>e.seq>archiveSeq);if(!fresh.length)return;try{const tx=db.transaction('events','readwrite'),s=tx.objectStore('events');fresh.forEach(e=>s.put({...e,key:worldKey+':'+String(e.seq).padStart(14,'0'),world:worldKey}));tx.oncomplete=()=>{archiveSeq=Math.max(archiveSeq,...fresh.map(e=>e.seq))};tx.onerror=()=>{db=null;storageMessage();toast('歷史寫入失敗；請匯出存檔保留目前進度。')}}catch(e){db=null;storageMessage()}}
function save(silent=false){if(!state)return;archiveEvents();const ok=store('wog-save-v1',JSON.stringify({format:'WorldOfGod',state,seen,worldKey}));if(!silent)toast(ok?'世界已儲存在這個瀏覽器。':'儲存失敗，請按「匯出」下載存檔。');}
function restore(data){const s=data.state||data;const valid=WoG.validateSave(s);if(valid===false||valid?.ok===false)throw new Error(valid?.errors?.join('；')||'存檔格式不相容');state=s;seen={miracle:data.seen?.miracle===true,oracle:data.seen?.oracle===true,consequence:data.seen?.consequence===true};worldKey=typeof data.worldKey==='string'&&data.worldKey.length<200?data.worldKey:`import-${Date.now()}`;archiveSeq=0;selectedTown=state.towns[0].id;selectedPerson=null;paused=true;markers=[];armed=null;renderUI();draw(0);archiveEvents();}
function load(){const raw=read('wog-save-v1');if(!raw)return toast('還沒有存檔。先開始一個世界，或匯入 JSON。');try{restore(JSON.parse(raw));toast('世界已讀取，時間暫停中。')}catch(e){toast('無法讀取：'+e.message)}}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function getTown(){return state.towns.find(t=>t.id===selectedTown)||state.towns[0]}
function townPeople(t){return state.people.filter(p=>p.town===t.id)}
function localTiles(t){return state.tiles.filter(c=>c.kind==='field'&&Math.hypot(c.x-t.x,c.y-t.y)<9)}
function config(){return {preset,seed:$('seed').value.trim()||'river-dawn-01',difficulty:$('difficulty').value,moisture:Number($('wet').value)/100,food:Number($('startFood').value),belief:Number($('belief').value)/100}}
function fillConfig(c){preset=c.preset||'valley';$('seed').value=c.seed||'river-dawn-01';$('difficulty').value=c.difficulty||'relaxed';$('wet').value=Math.round((c.moisture??.65)*100);$('startFood').value=c.food??80;$('belief').value=Math.round((c.belief??.28)*100);document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('selected',b.dataset.preset===preset));updateOutputs()}
function updateOutputs(){$('wetOut').textContent=$('wet').value+'%';$('foodOut').textContent=$('startFood').value;$('beliefOut').textContent=$('belief').value+'%'}
function begin(c){state=WoG.create(c);worldKey=`${Date.now()}-${c.seed}`;archiveSeq=0;selectedTown=state.towns[0].id;selectedPerson=null;seen={miracle:false,oracle:false,consequence:false};paused=false;markers=[];armed=null;save(true);renderUI();toast('歷史開始了。觀察糧食與土壤，再決定是否介入。');}
function setAction(type){if(!state)return;const t=getTown();if(type==='rain'){armed=armed==='rain'?null:'rain';renderUI();return;}const r=WoG.act(state,type,t.id);if(!r.ok)return toast(r.message||'現在無法施展');if(type==='oracle')seen.oracle=true;else seen.miracle=true;markers.push({x:t.x,y:t.y,life:180,type});toast(r.message||'神意已傳入世界。');archiveEvents();renderUI();}
function eventHTML(e){const reason=e.reason||e.reasons||e.cause;return `<div class="event"><small>第 ${Math.floor(e.tick/12)+1} 日 · #${e.seq}</small><p>${esc(e.text)}</p>${reason?`<details><summary>為什麼？</summary>${esc(Array.isArray(reason)?reason.join('；'):typeof reason==='object'?JSON.stringify(reason):reason)}</details>`:''}</div>`}
function renderUI(){if(!state)return;const st=WoG.stats(state),t=getTown(),ps=townPeople(t),tiles=localTiles(t);$('worldTitle').textContent=names[state.config.preset]+' · '+(state.tick<72?'初光':'流動的歷史');$('population').textContent=st.population;$('followers').textContent=st.followers;$('devotion').textContent=num(st.devotion,1);$('power').textContent=num(state.power,1);$('powerBar').style.width=Math.min(100,state.power)+'%';$('day').textContent=`第 ${Math.floor(state.tick/12)+1} 日`;$('weather').textContent=({drought:'乾旱',dry:'乾旱',rain:'降雨',mild:'和暖',clear:'晴朗',rainy:'雨季'}[state.weather?.kind]||state.weather?.kind||'晴朗');$('pause').textContent=paused?'▶ 繼續歷史':'Ⅱ 暫停';$('townName').textContent=t.name;$('townIndex').textContent='0'+(state.towns.indexOf(t)+1);$('food').textContent=num(t.food);$('moisture').textContent=num(100*(tiles.reduce((s,c)=>s+c.moisture,0)/(tiles.length||1)))+'%';const avg=ps.reduce((s,p)=>s+p.faith,0)/(ps.length||1);$('faith').textContent=num(avg*100)+'%';$('townSummary').textContent=t.food<25?'糧倉見底，人們正在重新安排生活。':t.food<65?'糧食需要照顧。居民正自行尋找出路。':'河岸生活暫時安穩，日常仍在繼續。';
const o=t.oracle;$('oracleInfo').innerHTML=o?`<strong>◈ 糧食優先 · ${esc(stageNames[o.stage]||o.stage)}</strong><span>${esc(o.reason||'人們正在思考你的意思。')}</span><div class="oracle-steps">${(o.history||[]).map(h=>esc(stageNames[h.stage]||h.stage)).join(' → ')}</div>`:'';
if(o&&['completed','failed','consequences'].includes(o.stage))seen.consequence=true;
$('people').innerHTML=ps.map(p=>`<button class="person ${p.faith>=.35?'believer':''} ${p.id===selectedPerson?'selected':''}" data-person="${esc(p.id)}"><span class="dot"></span>${esc(p.name)}<small>${esc(taskNames[p.task]||p.task)}</small></button>`).join('');
const p=ps.find(p=>p.id===selectedPerson);$('personDetail').textContent=p?`${p.name} · 信仰 ${num(p.faith*100)}% · 飢餓 ${num(p.hunger*100)}% · ${p.reason||p.taskReason||'根據飢餓、體力與信仰，自行選擇下一步。'}`:`${ps.length} 位居民，${state.households.filter(h=>h.town===t.id).length} 個家戶。金色標記代表信徒，並非所有人都相信你。`;
$('events').innerHTML=state.events.slice(-5).reverse().map(eventHTML).join('');$('goals').innerHTML=[['觀察生活',state.tick>=12],['帶來一場神蹟',seen.miracle],['傳下神諭',seen.oracle],['看見回應',seen.consequence]].map(([x,v])=>`<span class="goal ${v?'done':''}">${x}</span>`).join('');
$('rain').classList.toggle('armed',armed==='rain');$('rain').disabled=state.power<18;$('bless').disabled=state.power<14;$('oracle').disabled=state.power<10||!!(o&&o.stage!=='consequences');$('mapHint').textContent=armed?'點選土地，讓雨滋潤周圍農田 · Esc 取消':'點選聚落或居民，聆聽這個世界';canvas.style.cursor=armed?'crosshair':'pointer';$('status').textContent=paused?'時間已暫停 · 空白鍵繼續':`神性火種仍在 · 神力 +${num(st.powerRate||0,2)} / 刻 · ${speed}× 時間`;storageMessage();}
const C=30;function shade(x,y){return ((x*137+y*73+x*y*17)%23)/23}
function draw(time){if(!state)return;frame++;const w=state.width,h=state.height;ctx.clearRect(0,0,1200,780);ctx.fillStyle='#658d85';ctx.fillRect(0,0,1200,780);
for(const t of state.tiles){const x=t.x*C,y=t.y*C,n=shade(t.x,t.y),m=t.moisture??.5;if(t.kind==='water'){ctx.fillStyle=`hsl(171,${23+n*8}%,${43+n*7}%)`;ctx.fillRect(x,y,C+1,C+1);if(n>.65){ctx.strokeStyle='#a9d1bb50';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+5,y+13+Math.sin(time/1300+t.x)*2);ctx.lineTo(x+22,y+13);ctx.stroke();}continue;}
const light=43+m*16+n*5;ctx.fillStyle=t.kind==='hill'?`hsl(86,16%,${light-6}%)`:t.kind==='field'?`hsl(${43+m*15},35%,${50+m*11+n*4}%)`:`hsl(${77+m*20},${18+m*9}%,${light}%)`;ctx.fillRect(x,y,C+1,C+1);
if(t.kind==='field'){ctx.strokeStyle='#73865180';ctx.lineWidth=2;for(let k=5;k<28;k+=6){ctx.beginPath();ctx.moveTo(x+3,y+k);ctx.lineTo(x+27,y+k);ctx.stroke()}if(t.growth>.3){ctx.fillStyle=t.growth>.7?'#e4d48b':'#9fae6f';for(let k=5;k<28;k+=7)for(let j=6;j<28;j+=8){ctx.fillRect(x+j,y+k,2,Math.max(2,t.growth*5))}}}
else if(t.kind==='hill'){ctx.fillStyle='#818b71';ctx.beginPath();ctx.moveTo(x+1,y+26);ctx.lineTo(x+14,y+5);ctx.lineTo(x+30,y+26);ctx.fill();ctx.fillStyle='#a3aa87';ctx.beginPath();ctx.moveTo(x+14,y+5);ctx.lineTo(x+19,y+26);ctx.lineTo(x+30,y+26);ctx.fill()}
else if(n>.85){ctx.strokeStyle='#e1e3aa50';ctx.beginPath();ctx.moveTo(x+10,y+20);ctx.lineTo(x+11,y+15);ctx.moveTo(x+13,y+20);ctx.lineTo(x+15,y+17);ctx.stroke()}}
// Riverbank edges, soft paths, and groves.
for(const t of state.tiles){if(t.kind==='water')continue;const right=state.tiles[t.y*w+t.x+1],down=state.tiles[(t.y+1)*w+t.x];ctx.strokeStyle='#d1d0a46b';ctx.lineWidth=2;if(t.x<w-1&&right?.kind==='water'){ctx.beginPath();ctx.moveTo((t.x+1)*C,t.y*C);ctx.lineTo((t.x+1)*C,(t.y+1)*C);ctx.stroke()}if(t.y<h-1&&down?.kind==='water'){ctx.beginPath();ctx.moveTo(t.x*C,(t.y+1)*C);ctx.lineTo((t.x+1)*C,(t.y+1)*C);ctx.stroke()}}
for(const t of state.towns){const x=(t.x+.5)*C,y=(t.y+.5)*C;ctx.strokeStyle='#d0c49d70';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x-65,y+22);ctx.lineTo(x+55,y+22);ctx.moveTo(x,y-38);ctx.lineTo(x,y+50);ctx.stroke();if(t.id===getTown().id){ctx.strokeStyle='#f1e8b075';ctx.lineWidth=1.5;ctx.setLineDash([5,7]);ctx.beginPath();ctx.ellipse(x,y,104,77,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}
for(let i=0;i<4;i++){const hx=x+(i%2)*65-47,hy=y+Math.floor(i/2)*49-34;house(hx,hy,i)}ctx.fillStyle='#64775a';ctx.beginPath();ctx.ellipse(x+3,y+10,12,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d9cda6';ctx.fillRect(x-4,y-8,8,16);ctx.fillStyle='#f1e3b2';ctx.beginPath();ctx.arc(x,y-10,4,0,Math.PI*2);ctx.fill();if(t.blessing>0){ctx.strokeStyle='#f4df9180';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,90+Math.sin(time/700)*4,0,Math.PI*2);ctx.stroke()}}
for(const t of state.tiles){if(t.kind!=='forest')continue;const x=(t.x+.5)*C,y=(t.y+.5)*C,n=shade(t.x,t.y);ctx.fillStyle='#324b4326';ctx.beginPath();ctx.ellipse(x+4,y+6,11,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5b6950';ctx.fillRect(x-2,y-3,4,12);ctx.fillStyle=n>.5?'#3f6951':'#547951';ctx.beginPath();ctx.arc(x,y-6,10+n*3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#71946580';ctx.beginPath();ctx.arc(x-3,y-9,5,0,Math.PI*2);ctx.fill()}
for(const p of state.people){const x=(p.x+.5)*C,y=(p.y+.5)*C;ctx.fillStyle='#233d3333';ctx.beginPath();ctx.ellipse(x+2,y+7,5,3,0,0,Math.PI*2);ctx.fill();if(p.faith>=.35){ctx.strokeStyle='#f2dc9790';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y-3,8,0,Math.PI*2);ctx.stroke()}ctx.fillStyle=p.faith>=.35?'#dac282':'#e5e2c0';ctx.fillRect(x-3,y-1,6,7);ctx.fillStyle='#554e3d';ctx.fillRect(x-3,y-8,6,5);ctx.fillStyle='#d9b991';ctx.fillRect(x-2,y-5,4,4);if(p.id===selectedPerson){ctx.strokeStyle='#fff4b4';ctx.strokeRect(x-7,y-11,14,21)}}
for(const t of state.towns){const x=(t.x+.5)*C,y=(t.y+.5)*C;ctx.font='15px sans-serif';const tw=ctx.measureText(t.name).width;ctx.fillStyle=t.id===getTown().id?'#f4f1dcef':'#f4f1dccc';ctx.fillRect(x-tw/2-13,y-75,tw+26,29);ctx.fillStyle='#355144';ctx.textAlign='center';ctx.fillText(t.name,x,y-55)}
if(armed&&hover){ctx.fillStyle='#c2e4d02a';ctx.strokeStyle='#f5f4cfb0';ctx.lineWidth=2;ctx.beginPath();ctx.arc(hover.x*C,hover.y*C,7*C,0,Math.PI*2);ctx.fill();ctx.stroke()}
markers=markers.filter(m=>m.life>0);for(const m of markers){m.life--;const x=(m.x+.5)*C,y=(m.y+.5)*C;ctx.strokeStyle=m.type==='rain'?`rgba(209,243,231,${m.life/200})`:`rgba(255,229,150,${m.life/200})`;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,40+(180-m.life)*1.1,0,Math.PI*2);ctx.stroke();if(m.type==='rain'){ctx.lineWidth=1.5;for(let i=0;i<45;i++){const rx=x+Math.sin(i*29)*140,ry=y+((i*37+frame*5)%230)-115;ctx.beginPath();ctx.moveTo(rx,ry);ctx.lineTo(rx-4,ry+12);ctx.stroke()}}}
ctx.fillStyle='#203c3110';ctx.fillRect(0,0,1200,780);
}
function house(x,y,i){ctx.fillStyle='#2e403329';ctx.beginPath();ctx.ellipse(x+9,y+14,22,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d4ca9c';ctx.fillRect(x-14,y-4,28,20);ctx.fillStyle='#b3ad86';ctx.fillRect(x+5,y-4,9,20);ctx.fillStyle=i%2?'#7b7761':'#89735b';ctx.beginPath();ctx.moveTo(x-20,y-3);ctx.lineTo(x,y-21);ctx.lineTo(x+20,y-3);ctx.closePath();ctx.fill();ctx.strokeStyle='#b2a082';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-14,y-4);ctx.lineTo(x,y-17);ctx.lineTo(x+14,y-4);ctx.stroke();ctx.fillStyle='#676b51';ctx.fillRect(x-4,y+4,7,12);ctx.fillStyle='#e5d7a3';ctx.fillRect(x-11,y+3,4,5)}
function loop(t){const dt=Math.min(250,t-(lastFrame||t));lastFrame=t;if(state&&!paused&&!$('genesisDialog').open&&!$('infoDialog').open){accum+=dt*speed;if(accum>=500){const count=Math.floor(accum/500);accum-=count*500;for(let i=0;i<count;i++){WoG.step(state,1);archiveEvents()}renderUI();if(state.tick%24===0)save(true)}}draw(t);requestAnimationFrame(loop)}
$('begin').addEventListener('click',e=>{e.preventDefault();begin(config());$('genesisDialog').close()});$('closeGenesis').onclick=()=>$('genesisDialog').close();$('genesis').onclick=()=>{paused=true;renderUI();$('genesisDialog').showModal()};$('pause').onclick=()=>{paused=!paused;renderUI()};document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));renderUI()});
for(const id of ['rain','bless','oracle'])$(id).onclick=()=>setAction(id);$('save').onclick=()=>save();$('load').onclick=load;$('export').onclick=()=>{if(state)download('world-of-god-save.json',JSON.stringify({format:'WorldOfGod',state,seen,worldKey},null,2));toast('已匯出目前世界與近期歷史。更多近期事件可從「歷史檔案」匯出。')};$('import').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>5e6)return toast('檔案太大，請選擇 5 MB 以下的遊戲存檔。');try{const data=JSON.parse(await file.text());restore(data.state?{...data,worldKey:`import-${Date.now()}`}:{state:data,worldKey:`import-${Date.now()}`});save(true);toast('已匯入世界，時間暫停中。')}catch(err){toast('無法匯入：'+err.message)}e.target.value=''};
$('people').onclick=e=>{const b=e.target.closest('[data-person]');if(!b)return;selectedPerson=state.people.find(p=>String(p.id)===b.dataset.person)?.id;renderUI()};canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();hover={x:(e.clientX-r.left)/r.width*state.width,y:(e.clientY-r.top)/r.height*state.height}});canvas.addEventListener('pointerleave',()=>hover=null);canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*state.width,y=(e.clientY-r.top)/r.height*state.height;if(armed){const result=WoG.act(state,'rain',{x:Math.floor(x),y:Math.floor(y)});if(result.ok){seen.miracle=true;markers.push({x,y,life:180,type:'rain'});armed=null;archiveEvents()}toast(result.message||'雨落下了。');renderUI();return;}const p=state.people.find(p=>Math.hypot(p.x+.5-x,p.y+.5-y)<.65);const t=p?state.towns.find(t=>t.id===p.town):state.towns.reduce((a,b)=>Math.hypot(a.x-x,a.y-y)<Math.hypot(b.x-x,b.y-y)?a:b);selectedTown=t.id;selectedPerson=p?.id??null;renderUI()});
$('saveConfig').onclick=()=>toast(store('wog-config',JSON.stringify(config()))?'自訂世界設定已儲存。':'無法儲存自訂設定。');$('loadConfig').onclick=()=>{try{const c=JSON.parse(read('wog-config'));if(!c)return toast('還沒有自訂設定。');fillConfig(c);toast('已讀取自訂設定。')}catch(e){toast('設定格式無法讀取。')}};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=b.dataset.preset;fillConfig({preset:p,seed:$('seed').value,difficulty:$('difficulty').value,moisture:p==='dry'?.28:p==='islands'?.7:.65,food:p==='dry'?45:80,belief:.28})});['wet','startFood','belief'].forEach(id=>$(id).oninput=updateOutputs);
function info(title,html){$('infoLabel').textContent=title;$('infoBody').innerHTML=html;$('infoDialog').showModal()}$('closeInfo').onclick=()=>$('infoDialog').close();$('guide').onclick=()=>info('遊玩指南 / HOW TO PLAY',`<h3>你是神，世界有自己的意志。</h3><ol><li>開始歷史，觀察兩座聚落的糧倉、土壤與居民選擇。點選地圖或人物可查看詳情。</li><li>按「喚雨」，再點土地。雨水先改善土壤，作物成長、居民採收後才會變成糧食。</li><li>點選一座聚落，給予「豐收祝福」，或傳下「糧食優先」神諭。人們可能接受、暫緩或拒絕。</li><li>在右側追蹤神諭階段與世界事件。1× 約每秒 2 刻，12 刻為一日。空白鍵暫停，1 / 2 / 3 選擇神力，Esc 取消喚雨。</li><li>神力由信仰與緩慢恢復的神性火種產生。個人信仰 ≥ 35% 算作信徒；奉獻是居民的宗教貢獻。</li></ol><p>世界每約 12 秒自動儲存，亦可手動儲存。瀏覽器清除資料會移除進度；請匯出 JSON 備份。雙擊 HTML 若無法持久儲存，請使用 localhost 方式執行。</p><p>這是一個小型可玩原型。家戶只有成員結構；繁衍、遷徙、政治、建築系統與完整跨版本回放尚未實作。</p>`);
$('archive').onclick=async()=>{let events=state.events;if(db){try{events=await new Promise((resolve,reject)=>{const rows=[];const req=db.transaction('events').objectStore('events').index('world').openCursor(IDBKeyRange.only(worldKey),'prev');req.onsuccess=()=>{const cur=req.result;if(!cur||rows.length>=200)return resolve(rows);rows.push(cur.value);cur.continue()};req.onerror=reject})}catch(e){toast('無法讀取長期歷史，改顯示近期事件。')}}const snapshot=events.sort((a,b)=>b.seq-a.seq);info('歷史檔案 / CHRONICLE',`<h3>${esc(getTown().name)}所在的世界</h3><p>顯示本機檔案中的最近 ${snapshot.length} 則事件（最多 200 則）。近期記憶最多保留 80 則，較早事件存放在本機歷史檔案。</p><button id="downloadHistory">匯出這些事件 JSON</button><div class="archive-list">${snapshot.slice(0,200).map(eventHTML).join('')}</div>`);$('downloadHistory').onclick=()=>download('world-of-god-history.json',JSON.stringify(snapshot,null,2))};
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||$('genesisDialog').open||$('infoDialog').open)return;if(e.code==='Space'){e.preventDefault();paused=!paused;renderUI()}if(e.key==='Escape'){armed=null;renderUI()}if(e.key==='1')setAction('rain');if(e.key==='2')setAction('bless');if(e.key==='3')setAction('oracle')});window.addEventListener('beforeunload',()=>save(true));
state=WoG.create(config());selectedTown=state.towns[0].id;worldKey='preview';renderUI();openDB();const saved=read('wog-save-v1');if(saved){try{restore(JSON.parse(saved));toast('歡迎回來。已讀取上次的世界，時間暫停中。')}catch(e){$('genesisDialog').showModal()}}else $('genesisDialog').showModal();requestAnimationFrame(loop);
})();
