// Browser-independent UI contract checks. This is NOT a real browser layout test.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
function harness(){
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),els=new Map(),storage=new Map(),listeners={};let raf;
 const ctx=new Proxy({measureText:t=>({width:t.length*15})},{get:(o,k)=>o[k]??(()=>{})});
 function elem(id){return {id,value:({seed:'river-dawn-01',difficulty:'relaxed',wet:'65',startFood:'80',belief:'28'})[id]||'',style:{},dataset:{},classList:{toggle(){},add(){},remove(){}},textContent:'',innerHTML:'',open:false,disabled:false,files:[],events:{},addEventListener(k,f){this.events[k]=f},getContext(){return ctx},showModal(){this.open=true},close(){this.open=false},click(){this.onclick?.({preventDefault(){}});this.events.click?.({preventDefault(){}})},getBoundingClientRect(){return {left:0,top:0,width:1200,height:780}}};}
 for(const m of html.matchAll(/id="([^"]+)"/g))els.set(m[1],elem(m[1]));
 const speed=[1,3,6].map(n=>Object.assign(elem('speed'+n),{dataset:{speed:String(n)}}));const presets=['valley','dry','islands'].map(n=>Object.assign(elem(n),{dataset:{preset:n}}));
 const win={document:{getElementById:id=>els.get(id)||null,querySelectorAll:s=>s==='[data-speed]'?speed:s==='[data-preset]'?presets:[],addEventListener:(k,f)=>listeners[k]=f,createElement:()=>elem('download')},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},indexedDB:{open(){throw Error('blocked for persistence fallback test')}},setTimeout:()=>1,clearTimeout(){},requestAnimationFrame:f=>raf=f,Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},console,Date};win.window=win;win.addEventListener=(k,f)=>listeners[k]=f;vm.createContext(win);vm.runInContext(fs.readFileSync(path.join(root,'core.js'),'utf8'),win);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),win);
 return {els,storage,win,step:t=>raf(t),presets,speed};
}
test('all app element references exist in HTML',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),app=fs.readFileSync(path.join(root,'app.js'),'utf8');const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(x=>x[1]));ids.add('downloadHistory');for(const m of app.matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.has(m[1]),m[1]);});
test('UI starts in Genesis; begin, rain, oracle, save, load, pause and custom settings execute',()=>{const h=harness(),e=h.els;assert.equal(e.get('genesisDialog').open,true);e.get('begin').click();assert.equal(e.get('genesisDialog').open,false);assert.equal(e.get('population').textContent,24);h.step(1000);h.step(1250);h.step(1500);e.get('pause').click();e.get('rain').click();e.get('world').events.click({clientX:315,clientY:375});e.get('oracle').click();assert.match(e.get('oracleInfo').innerHTML,/已傳下/);e.get('save').click();let save=JSON.parse(h.storage.get('wog-save-v1'));assert.equal(save.seen.miracle,true);assert.equal(save.seen.oracle,true);assert.equal(save.state.actions.length,2);assert.ok(save.state.power<15);e.get('load').click();assert.match(e.get('oracleInfo').innerHTML,/已傳下/);assert.match(e.get('pause').textContent,/繼續/);h.presets[1].click();e.get('saveConfig').click();assert.equal(JSON.parse(h.storage.get('wog-config')).preset,'dry');assert.equal(e.get('wet').value,28);e.get('loadConfig').click();});
test('malformed import/save is rejected without replacing running world',()=>{const h=harness();h.els.get('begin').click();h.storage.set('wog-save-v1','{"state":{"version":1}}');h.els.get('load').click();assert.match(h.els.get('toast').textContent,/無法讀取/);assert.equal(h.els.get('population').textContent,24);});
test('standalone build contains no external script, CSS, font or image resources',()=>{require('../build.cjs');const html=fs.readFileSync(path.join(root,'World-of-God.html'),'utf8');assert.doesNotMatch(html,/<script[^>]*\bsrc=|<link[^>]*stylesheet|@import|<img[^>]*\bsrc=/i);assert.match(html,/globalThis/);assert.match(html,/GENESIS/);});
